### ISSUE TITLE
debug-mode documentation

### ISSUE THREAD

**Issue by notpeter** [trbs/bucky#60]
I just discovered that when running --debug bucky doesn't actually ship metrics and instead just prints to stdout.  I found this behavior surprising.  Can someone confirm that is correct?

If so, I'll happily submit a PR which notes that in the --help and readme documentation. And also perhaps mentions using --log-level=DEBUG for live-ish debugging.

**Comment by trbs** [comment]
Yeah that's correct.

Thanks for helping and clarifying this !
Will merge the PR as soon as I see it :)

**Comment by notpeter** [comment]
I think it might be worth offering a non 'dry-run' debug mode where you can both ship metrics to graphite and see super verbose output.  I may take a crack at that, but it'll be as a distinct issue.

**Comment by trbs** [comment]
Thkins we could add ```--dry-run``` to disable sending to carbon and keep ```--debug``` to enable debug information on the stdout.
